[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.30'
optimizer = true
optimizer_runs = 1000
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
local = "${ANVIL_RPC_URL}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

