[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.30'
optimizer = true
optimizer_runs = 100000
etherscan_api_key = "${ETHERSCAN_API_KEY}"
gas_reports = ["MiniMart"]
evm_version = "cancun"
sender = "0x4FBcb0ABB61a366D9742009BB986B9C0Eba9FEF9"

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

